branch-defaults:
  master:
    environment: Online-Study-Game
    group_suffix: null
global:
  application_name: Online-Study-Game
  branch: null
  default_platform: Python 3.6
  default_region: us-east-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: um-online-study-game
  repository: null
  workspace_type: Application
